<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => '别名',
    'Answer' => '回答',
    'Answer failed. Please try again later.' => '回答失败。请稍后再试。',
    'Answer to adopt success.' => '采纳回答成功',
    'Answers' => '回答',
    'Ask a Question' => '提问',
    'Content' => '内容',
    'Created At' => '创建时间',
    'Delete' => '删除',
    'Best answer'=>'最佳答案',
    '{n, plural, =0{No comment} =1{One comment} other{# reviews}}'=>'{n, plural, =0{暂无评论} =1{1 条评论} other{# 条评论}}',
    'Add details to get a more accurate answer.'=>'补充细节，以得到更准确的答案',
    'Operation completed.'=>'操作完成。',
    'Edit' => '修改',
    'No introduction'=>'暂无介绍',
    'Question & Answer'=>'问答',
    'Edit Answer' => '编辑回答',
    'Hot question' => '热门问题',
    'ID' => '',
    'Update Question'=>'编辑问题',
    'Reward' => '悬赏',
    'My Answer' => '我的回答',
    'Confirm Changes' => '确认修改',
    'Hide' => '匿名',
    'Point' => '积分',
    'Insufficient points, please recharge.' => '积分不足，请先充值。',
    'Please enter the correct points.' => '请输入正确的积分。',
    'Markdown powered content' => '支持 Markdown 语法',
    'New question' => '最新的',
    'No popular questions' => '',
    'Popular Questions' => '热门问题',
    'Popular tags' => '热门话题',
    'Publish' => '发布',
    'Question' => '问题',
    'Questions' => '问题',
    'Default Sort' => '默认排序',
    'Time Sort' => '时间排序',
    'Remove' => '删除',
    'Reward question' => '悬赏的',
    'Status' => '状态',
    'Sure?' => '你确定？',
    'Tag' => '标签',
    'Tags' => '标签',
    'Title' => '问题',
    'Unanswered question' => '未回答的',
    'Update' => '更新',
    'User' => '用户',
    'Views' => '查看',
    'What\'s your question? Be specific.' => '你的问题是什么？',
    '{n, plural, =0{No answers yet} =1{One answer} other{# answers}}' => '{n, plural, =0{0 个回答} =1{1 个回答} other{# 个回答}}',
];
