<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => '别名',
    'Answer' => '回答',
    'Answer failed. Please try again later.' => '回答失败。请稍后再试。',
    'Answer to adopt success.' => '采纳回答成功',
    'Answers' => '回答',
    'Ask a Question' => '提问',
    'Content' => '内容',
    'Created At' => '创建时间',
    'Delete' => '删除',
    'Edit' => '修改',
    'Hot question' => '热门问题',
    'ID' => '',
    'Reward' => '悬赏',
    'Hide' => '匿名',
    'Markdown powered content' => '支持 Markdown 语法',
    'New question' => '最新的',
    'No popular questions' => '',
    'Popular Questions' => '热门问题',
    'Popular tags' => '热门话题',
    'Publish' => '发布',
    'Question' => '问题',
    'Questions' => '问题',
    'Default Sort' => '默认排序',
    'Time Sort' => '时间排序',
    'Remove' => '删除',
    'Reward question' => '悬赏的',
    'Status' => '状态',
    'Sure?' => '你确定？',
    'Tag' => '标签',
    'Tags' => '标签',
    'Title' => '问题',
    'Unanswered question' => '未回答的',
    'Update' => '更新',
    'User' => '用户',
    'Views' => '查看',
    'What\'s your question? Be specific.' => '你的问题是什么？',
    '{n, plural, =0{No answers yet} =1{One answer} other{# answers}}' => '{n, plural, =0{0 个回答} =1{1 个回答} other{# 个回答}}',
];
