<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'His Answers' => '他的回答',
    'His Questions' => '他的提问',
    'ID' => '',
    'My Answers' => '我的回答',
    'Delete' => '@@删除@@',
    'Markdown powered content' => '@@支持 Markdown 语法@@',
    'Popular tags' => '@@热门话题@@',
    'Publish' => '@@发布@@',
    'Question' => '@@问题@@',
    'Tag' => '@@标签@@',
    'Update' => '@@更新@@',
    'User' => '@@用户@@',
    'What\'s your question? Be specific.' => '@@你的问题是什么？@@',
    'Add details to get a more accurate answer.' => '补充细节，以得到更准确的答案',
    'Adopte failed. Please try again later.' => '操作失败，请重试！',
    'Alias' => '别名',
    'Answer' => '回答',
    'Answer to adopt success.' => '采纳回答成功',
    'Answers' => '回答',
    'Are you sure you want to delete this item?' => '你确定要删除该项目？',
    'Ask a Question' => '提问',
    'Batch Deletion' => '批量删除',
    'Best answer' => '最佳答案',
    'Collections' => '收藏',
    'Comments' => '评论',
    'Confirm Changes' => '确认修改',
    'Content' => '内容',
    'Created At' => '创建时间',
    'Default Sort' => '默认排序',
    'Delete Question' => '删除问题',
    'Edit' => '修改',
    'Edit Answer' => '编辑回答',
    'Followers' => '关注',
    'Hide' => '匿名',
    'Hot question' => '热门问题',
    'Insufficient points, please recharge.' => '积分不足，请先充值。',
    'Manage Question' => '问题管理',
    'My Answer' => '我的回答',
    'My Questions' => '我的提问',
    'New question' => '最新的',
    'No introduction' => '暂无介绍',
    'No popular questions' => '暂无热门问题',
    'Operation' => '操作',
    'Operation completed.' => '操作完成。',
    'Please enter the correct points.' => '请输入正确的积分。',
    'Point' => '积分',
    'Popular Questions' => '热门问题',
    'Question & Answer' => '问答',
    'Questions' => '问题',
    'Remove' => '删除',
    'Reward' => '悬赏',
    'Reward question' => '悬赏的',
    'Status' => '状态',
    'Submit Question' => '提交问题',
    'Sure?' => '你确定？',
    'Tags' => '标签',
    'Time Sort' => '时间排序',
    'Title' => '问题',
    'Unanswered question' => '未回答的',
    'Update Question' => '编辑问题',
    'Updated At' => '更新时间',
    'Views' => '查看',
    'You can not take your own answer.' => '你不能自问自答。',
    '{n, plural, =0{No answers yet} =1{One answer} other{# answers}}' => '{n, plural, =0{0 个回答} =1{1 个回答} other{# 个回答}}',
    '{n, plural, =0{No comment} =1{One comment} other{# reviews}}' => '{n, plural, =0{暂无评论} =1{1 条评论} other{# 条评论}}',
];
